--Tsegawit Gebremedhin

-- Question 1: Enforce referential integrity by adding foreign key constraints
ALTER TABLE ORDERS
ADD CONSTRAINT fk_orders_user
FOREIGN KEY (USERID)
REFERENCES USERBASE(USERID);

ALTER TABLE REVIEWS
ADD CONSTRAINT fk_reviews_user
FOREIGN KEY (USERID)
REFERENCES USERBASE(USERID);

ALTER TABLE USERLIBRARY
ADD CONSTRAINT fk_userlibrary_user
FOREIGN KEY (USERID)
REFERENCES USERBASE(USERID);



-- Question 2: Display full name and username of users 18 or older
SELECT FIRSTNAME || ' ' || LASTNAME AS FULLNAME,
       USERNAME
FROM USERBASE
WHERE FLOOR(MONTHS_BETWEEN(SYSDATE, BIRTHDAY)/12) >= 18;



-- Question 3: Find maximum and average length of USERNAME
SELECT MAX(LENGTH(USERNAME)) AS MAX_LENGTH,
       ROUND(AVG(LENGTH(USERNAME)),2) AS AVG_LENGTH
FROM USERBASE;



-- Question 4: Display all security questions starting with 'What is' or 'What was'
SELECT QUESTION
FROM SECURITYQUESTION
WHERE QUESTION LIKE 'What is%' OR QUESTION LIKE 'What was%';



-- Question 5: Display PRODUCTCODE, lowest RATING, and number of reviews per product
SELECT PRODUCTCODE,
       MIN(RATING) AS LOWEST_RATING,
       COUNT(*) AS REVIEW_COUNT
FROM REVIEWS
GROUP BY PRODUCTCODE
ORDER BY REVIEW_COUNT DESC;



-- Question 6: Display PRODUCTCODE ranked at POSITION 1 and number of users
SELECT PRODUCTCODE,
       COUNT(USERID) AS NUM_USERS
FROM WISHLIST
WHERE POSITION = 1
GROUP BY PRODUCTCODE;



-- Question 7: Display USERID and total amount spent in ORDERS
SELECT USERID,
       SUM(PRICE) AS TOTAL_SPENT
FROM ORDERS
GROUP BY USERID;



-- Question 8: Display gross profits by PURCHASEDATE, sorted descending
SELECT PURCHASEDATE,
       SUM(PRICE) AS GROSS_PROFIT
FROM ORDERS
GROUP BY PURCHASEDATE
ORDER BY GROSS_PROFIT DESC;



-- Question 9: Top 5 games with most play time
SELECT PRODUCTCODE,
       SUM(HOURSPLAYED) AS TOTAL_HOURS
FROM USERLIBRARY
GROUP BY PRODUCTCODE
ORDER BY TOTAL_HOURS DESC
FETCH FIRST 5 ROWS ONLY;



-- Question 10: View of USERID and infraction count, highest first
CREATE OR REPLACE VIEW USER_INFRACTION_COUNT AS
SELECT USERID,
       COUNT(*) AS INFRACTION_COUNT
FROM INFRACTIONS
GROUP BY USERID
ORDER BY INFRACTION_COUNT DESC;



-- Question 11: View of USERID, RULENUM, and number of times broken
CREATE OR REPLACE VIEW USER_RULENUM_COUNT AS
SELECT USERID,
       RULENUM,
       COUNT(*) AS TIMES_BROKEN
FROM INFRACTIONS
GROUP BY USERID, RULENUM
ORDER BY USERID;



-- Question 12: Display RULENUM, PENALTY, and number of times PENALTY assigned
SELECT RULENUM,
       PENALTY,
       COUNT(*) AS TIMES_ASSIGNED
FROM INFRACTIONS
GROUP BY RULENUM, PENALTY;



-- Question 13: Average, max, min time between DATEUPDATED and DATESUBMITTED for CLOSED tickets
SELECT AVG(DATEUPDATED - DATESUBMITTED) AS AVG_DAYS,
       MAX(DATEUPDATED - DATESUBMITTED) AS MAX_DAYS,
       MIN(DATEUPDATED - DATESUBMITTED) AS MIN_DAYS
FROM TICKETS
WHERE STATUS = 'CLOSED';



-- Question 14: Count of ISSUE submissions for NEW tickets grouped by DATESUBMITTED
SELECT EMAIL,
       ISSUE,
       COUNT(*) AS ISSUE_COUNT,
       DATESUBMITTED
FROM TICKETS
WHERE STATUS = 'NEW'
GROUP BY EMAIL, ISSUE, DATESUBMITTED
ORDER BY ISSUE_COUNT DESC;



-- Question 15: Users with FIRSTNAME or LASTNAME in their PASSWORD
SELECT *
FROM USERBASE
WHERE PASSWORD LIKE '%' || FIRSTNAME || '%'
   OR PASSWORD LIKE '%' || LASTNAME || '%';



-- Question 16: Average PRICE of products by PUBLISHER, sorted alphabetically
SELECT PUBLISHER,
       ROUND(AVG(PRICE), 2) AS AVG_PRICE
FROM PRODUCT
GROUP BY PUBLISHER
ORDER BY PUBLISHER;



-- Question 17: View for products older than 5 years with 25% discount
CREATE OR REPLACE VIEW OLD_PRODUCTS_DISCOUNT AS
SELECT PRODUCTNAME,
       ROUND(PRICE * 0.75, 2) AS DISCOUNTED_PRICE
FROM PRODUCT
WHERE RELEASEDATE <= ADD_MONTHS(SYSDATE, -60);  -- 60 months = 5 years



-- Question 18: Maximum and minimum PRICE of products by GENRE
SELECT GENRE,
       MAX(PRICE) AS MAX_PRICE,
       MIN(PRICE) AS MIN_PRICE
FROM PRODUCT
GROUP BY GENRE;



-- Question 19: View for CHATLOG messages from last week
CREATE OR REPLACE VIEW RECENT_CHATLOG AS
SELECT *
FROM CHATLOG
WHERE DATESENT BETWEEN SYSDATE - 7 AND SYSDATE;



-- Question 20: View for users with penalties assigned in last month
CREATE OR REPLACE VIEW RECENT_PENALTIES AS
SELECT USERID,
       DATEASSIGNED,
       PENALTY
FROM INFRACTIONS
WHERE PENALTY IS NOT NULL
  AND DATEASSIGNED BETWEEN ADD_MONTHS(SYSDATE, -1) AND SYSDATE;