--Tsegawit Gebremedhin

-- Question 1: USERNAME and lowest RATING per user
SELECT U.USERNAME, MIN(R.RATING) AS LOWEST_RATING
FROM USERBASE U
JOIN REVIEWS R ON U.USERID = R.USERID
GROUP BY U.USERNAME;

-- Question 2: USER EMAIL, QUESTION, ANSWER
SELECT U.EMAIL, S.QUESTION, S.ANSWER
FROM USERBASE U
JOIN SECURITYQUESTION S ON U.USERID = S.USERID;

-- Question 3: FIRSTNAME, EMAIL, WALLETFUNDS of users without a wishlist
SELECT U.FIRSTNAME, U.EMAIL, U.WALLETFUNDS
FROM USERBASE U
LEFT JOIN WISHLIST W ON U.USERID = W.USERID
WHERE W.USERID IS NULL;

-- Question 4: USERNAME and number of products ordered
SELECT U.USERNAME, COUNT(O.ORDERID) AS NUM_PRODUCTS
FROM USERBASE U
LEFT JOIN ORDERS O ON U.USERID = O.USERID
GROUP BY U.USERNAME;

-- Question 5: Age of users who ordered a product in the last 6 months
SELECT U.FIRSTNAME, U.LASTNAME,
       FLOOR(MONTHS_BETWEEN(SYSDATE, U.BIRTHDAY)/12) AS AGE
FROM USERBASE U
JOIN ORDERS O ON U.USERID = O.USERID
WHERE O.PURCHASEDATE >= ADD_MONTHS(SYSDATE, -6);

-- Question 6: USERNAME and BIRTHDAY of user with highest friend count
SELECT U.USERNAME, U.BIRTHDAY
FROM USERBASE U
JOIN FRIENDSLIST F ON U.USERID = F.USERID
WHERE F.FRIENDCOUNT = (SELECT MAX(FRIENDCOUNT) FROM FRIENDSLIST);

-- Question 7: PRODUCTNAME, RELEASEDATE, PRICE, DESCRIPTION in WISHLIST
SELECT P.PRODUCTNAME, P.RELEASEDATE, P.PRICE, P.DESCRIPTION
FROM PRODUCTLIST P
JOIN WISHLIST W ON P.PRODUCTCODE = W.PRODUCTCODE;

-- Question 8: PRODUCTNAME, highest RATING, number of reviews
SELECT P.PRODUCTNAME,
       MAX(R.RATING) AS HIGHEST_RATING,
       COUNT(R.RATING) AS NUM_REVIEWS
FROM PRODUCTLIST P
JOIN REVIEWS R ON P.PRODUCTCODE = R.PRODUCTCODE
GROUP BY P.PRODUCTNAME
ORDER BY HIGHEST_RATING DESC;

-- Question 9: View of products with rating 5 or 1
CREATE OR REPLACE VIEW EXTREME_RATED_PRODUCTS AS
SELECT P.PRODUCTNAME, P.GENRE, R.RATING
FROM PRODUCTLIST P
JOIN REVIEWS R ON P.PRODUCTCODE = R.PRODUCTCODE
WHERE R.RATING IN (1,5)
ORDER BY R.RATING ASC;

-- Question 10: Count of products ordered grouped by GENRE
SELECT P.GENRE, COUNT(O.ORDERID) AS NUM_PRODUCTS
FROM PRODUCTLIST P
JOIN ORDERS O ON P.PRODUCTCODE = O.PRODUCTCODE
GROUP BY P.GENRE
ORDER BY P.GENRE ASC;

-- Question 11: View showing PUBLISHER, avg PRICE, sum HOURSPLAYED
CREATE OR REPLACE VIEW PUBLISHER_STATS AS
SELECT P.PUBLISHER,
       ROUND(AVG(P.PRICE),2) AS AVG_PRICE,
       SUM(UL.HOURSPLAYED) AS TOTAL_HOURS
FROM PRODUCTLIST P
LEFT JOIN USERLIBRARY UL ON P.PRODUCTCODE = UL.PRODUCTCODE
GROUP BY P.PUBLISHER;

-- Question 12: Sum of money spent by PUBLISHER
SELECT P.PUBLISHER, SUM(O.PRICE) AS TOTAL_SPENT
FROM PRODUCTLIST P
JOIN ORDERS O ON P.PRODUCTCODE = O.PRODUCTCODE
GROUP BY P.PUBLISHER
ORDER BY TOTAL_SPENT DESC;

-- ==============================
-- Questions 13–18 (TICKETS table does not exist)
-- ==============================

-- Question 13
-- Cannot run: TICKETS table does not exist in this schema.

-- Question 14
-- Cannot run: TICKETS table does not exist in this schema.

-- Question 15
-- Cannot run: TICKETS table does not exist in this schema.

-- Question 16
-- Cannot run: TICKETS table does not exist in this schema.

-- Question 17
-- Cannot run: TICKETS table does not exist in this schema.

-- Question 18
-- Cannot run: TICKETS table does not exist in this schema.

-- ==============================
-- Questions 19–24
-- ==============================

-- Question 19: View of CHATLOG messages from last week
CREATE OR REPLACE VIEW RECENT_CHATLOG AS
SELECT *
FROM CHATLOG
WHERE DATESENT >= SYSDATE - 7;

-- Question 20: View of users with PENALTY assigned in the last month
CREATE OR REPLACE VIEW RECENT_PENALTIES AS
SELECT USERID, DATEASSIGNED, PENALTY
FROM INFRACTIONS
WHERE PENALTY IS NOT NULL
  AND DATEASSIGNED >= ADD_MONTHS(SYSDATE, -1);

-- Question 21: USERNAME, DATEASSIGNED, and full guideline name
CREATE OR REPLACE VIEW USER_INFRACTIONS AS
SELECT U.USERNAME,
       I.DATEASSIGNED,
       I.RULENUM || ' ' || R.TITLE AS FULL_GUIDELINE
FROM INFRACTIONS I
JOIN USERBASE U ON I.USERID = U.USERID
JOIN RULES R ON I.RULENUM = R.RULENUM;

-- Question 22: Add SEVERITYPOINTS to INFRACTIONS and display total
ALTER TABLE INFRACTIONS ADD SEVERITYPOINTS NUMBER DEFAULT 0;

-- Example update for testing (optional)
UPDATE INFRACTIONS
SET SEVERITYPOINTS = 5
WHERE PENALTY IS NOT NULL;

-- Display sum of SEVERITYPOINTS per user
SELECT U.USERID,
       U.USERNAME,
       U.EMAIL,
       SUM(I.SEVERITYPOINTS) AS TOTAL_SEVERITY
FROM INFRACTIONS I
JOIN USERBASE U ON I.USERID = U.USERID
GROUP BY U.USERID, U.USERNAME, U.EMAIL;

-- Question 23: TITLE, DESCRIPTION, PENALTY
-- Create RULES table if it doesn't exist
CREATE TABLE RULES (
    RULENUM NUMBER PRIMARY KEY,
    TITLE VARCHAR2(100),
    DESCRIPTION VARCHAR2(255)
);

-- Insert example rules
INSERT INTO RULES (RULENUM, TITLE, DESCRIPTION) VALUES (1, 'No Cheating', 'Users must not cheat in games');
INSERT INTO RULES (RULENUM, TITLE, DESCRIPTION) VALUES (2, 'No Harassment', 'Users must not harass other users');
INSERT INTO RULES (RULENUM, TITLE, DESCRIPTION) VALUES (3, 'No Spam', 'Users must not spam chat or forums');
COMMIT;

-- Display TITLE, DESCRIPTION, PENALTY
SELECT R.TITLE,
       R.DESCRIPTION,
       I.PENALTY
FROM INFRACTIONS I
JOIN RULES R ON I.RULENUM = R.RULENUM;

-- Question 24: USERNAME and count of infractions >= 15
SELECT U.USERNAME,
       COUNT(I.INFRACTIONID) AS NUM_INFRACTIONS
FROM INFRACTIONS I
JOIN USERBASE U ON I.USERID = U.USERID
GROUP BY U.USERNAME
HAVING COUNT(I.INFRACTIONID) >= 15
ORDER BY NUM_INFRACTIONS DESC;