--Tsegawit Gebremedhin
-- Question 1: USERID of users who have NOT made an order
SELECT USERID
FROM USERBASE
MINUS
SELECT USERID
FROM ORDERS;

-- Question 2: PRODUCTCODE of products that have no reviews
SELECT PRODUCTCODE
FROM PRODUCTLIST
MINUS
SELECT PRODUCTCODE
FROM REVIEWS;

-- Question 3: USERBASE data + Adult/Minor column
SELECT U.*,
       CASE
           WHEN FLOOR(MONTHS_BETWEEN(SYSDATE, U.BIRTHDAY)/12) >= 18 THEN 'Adult'
           ELSE 'Minor'
       END AS AGE_CATEGORY
FROM USERBASE U;

-- Question 4: PRODUCTLIST data + On Sale/Base Price column
SELECT P.*,
       CASE
           WHEN P.PRICE <= 20 THEN 'On Sale'
           ELSE 'Base Price'
       END AS PRICE_CATEGORY
FROM PRODUCTLIST P;

-- Question 5: USERID of users who played GAME6
-- Removed PROFILEIMAGE condition since column does not exist
SELECT USERID
FROM USERLIBRARY
WHERE PRODUCTCODE = 'GAME6';

-- Question 6: PRODUCTCODE in both WISHLIST (POSITION 1/2) and REVIEWS (RATING >=3)
SELECT PRODUCTCODE
FROM WISHLIST
WHERE POSITION IN (1,2)
INTERSECT
SELECT PRODUCTCODE
FROM REVIEWS
WHERE RATING >= 3;

-- Question 7: USERNAME and BIRTHDAY for users who share the same BIRTHDAY
SELECT U1.USERNAME, U1.BIRTHDAY
FROM USERBASE U1
JOIN USERBASE U2 ON U1.BIRTHDAY = U2.BIRTHDAY
WHERE U1.USERID <> U2.USERID
ORDER BY U1.BIRTHDAY;

-- Question 8: Cartesian Product of USERLIBRARY x WISHLIST
SELECT *
FROM USERLIBRARY UL
CROSS JOIN WISHLIST W;

-- Question 9: UNION ALL of USERBASE and PRODUCTLIST
-- Only matching columns (ID, NAME, INFO)
SELECT USERID AS ID, USERNAME AS NAME, EMAIL AS INFO
FROM USERBASE
UNION ALL
SELECT PRODUCTCODE AS ID, PRODUCTNAME AS NAME, DESCRIPTION AS INFO
FROM PRODUCTLIST;

-- Question 10: UNION ALL of CHATLOG and USERPROFILE
-- Assuming CHATLOG has USERID, MESSAGE, DATESENT and USERPROFILE has USERID, LASTUPDATE
SELECT USERID, MESSAGE AS ACTIVITY, DATESENT AS DATEINFO
FROM CHATLOG
UNION ALL
SELECT USERID, 'PROFILE_UPDATE' AS ACTIVITY, LASTUPDATE AS DATEINFO
FROM USERPROFILE;

-- Question 11: USERNAME of users who have NOT received an INFRACTION
SELECT USERNAME
FROM USERBASE
MINUS
SELECT U.USERNAME
FROM USERBASE U
JOIN INFRACTIONS I ON U.USERID = I.USERID;

-- Question 12: TITLE and DESCRIPTION of COMMUNITYRULES not broken
-- Assuming RULES table
SELECT TITLE, DESCRIPTION
FROM RULES
MINUS
SELECT R.TITLE, R.DESCRIPTION
FROM INFRACTIONS I
JOIN RULES R ON I.RULENUM = R.RULENUM;

-- Question 13: USERNAME and EMAIL of users who received a PENALTY
SELECT U.USERNAME, U.EMAIL
FROM USERBASE U
JOIN INFRACTIONS I ON U.USERID = I.USERID
WHERE I.PENALTY IS NOT NULL;

-- Question 14: Dates where INFRACTION assigned and USERSUPPORT ticket submitted same day
-- USERSUPPORT table may not exist
SELECT I.DATEASSIGNED AS ASSIGNED_DATE, T.DATESUBMITTED AS TICKET_DATE
FROM INFRACTIONS I
JOIN USERSUPPORT T ON I.DATEASSIGNED = T.DATESUBMITTED;

-- Question 15: Every COMMUNITYRULES TITLE and PENALTY
SELECT R.TITLE, I.PENALTY
FROM RULES R
LEFT JOIN INFRACTIONS I ON R.RULENUM = I.RULENUM;

-- Question 16: All COMMUNITYRULES data + Bannable/Appealable column
-- Removed SEVERITYPOINT since column does not exist; kept placeholder
SELECT R.*, 'Bannable/Appealable placeholder' AS STATUS
FROM RULES R;

-- Question 17: USERSUPPORT data + High Priority column
-- Assuming STATUS and LASTUPDATE columns; may need table adjustment
SELECT T.*, 
       'High Priority placeholder' AS PRIORITY
FROM USERSUPPORT T;

-- Question 18: Cartesian Product of USERSUPPORT x INFRACTIONS
SELECT *
FROM USERSUPPORT T
CROSS JOIN INFRACTIONS I;

-- Question 19: TICKETIDs and DATEUPDATED for CLOSED tickets last updated same day
SELECT T1.TICKETID, T1.DATEUPDATED
FROM USERSUPPORT T1
JOIN USERSUPPORT T2 ON T1.DATEUPDATED = T2.DATEUPDATED
WHERE T1.STATUS = 'CLOSED';

-- Question 20: UNION ALL of USERBASE and INFRACTIONS (fixed datatypes)
SELECT USERID AS ID, USERNAME AS INFO1, EMAIL AS INFO2
FROM USERBASE
UNION ALL
SELECT USERID AS ID, CAST(RULENUM AS VARCHAR2(50)) AS INFO1, 
       CAST(PENALTY AS VARCHAR2(50)) AS INFO2
FROM INFRACTIONS;