-- Tsegawit Gebremedhin

-- 1. Users who have access to the database
SELECT USER_ID, USERNAME, CREATED, PASSWORD_CHANGE_DATE
FROM USER_USERS;

-- 2. Tables present in the database
SELECT *
FROM USER_TABLES;

-- 3. Describe tables
DESCRIBE ORDERS;
DESCRIBE PRODUCTLIST;
DESCRIBE REVIEWS;
DESCRIBE STOREFRONT;
DESCRIBE USERBASE;
DESCRIBE USERLIBRARY;

-- 4. Display all data in tables
SELECT * FROM ORDERS;
SELECT * FROM PRODUCTLIST;
SELECT * FROM REVIEWS;
SELECT * FROM STOREFRONT;
SELECT * FROM USERBASE;
SELECT * FROM USERLIBRARY;

-- 5. Constraints in the database
SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE, STATUS
FROM USER_CONSTRAINTS;

-- 6. Views present in the database
SELECT VIEW_NAME, TEXT
FROM USER_VIEWS;

-- 7. Usernames in alphabetical order
SELECT USERNAME
FROM USERBASE
ORDER BY USERNAME;

-- 8. Users with yahoo email
SELECT FIRSTNAME, LASTNAME, USERNAME, PASSWORD, EMAIL
FROM USERBASE
WHERE EMAIL LIKE '%yahoo%';

-- 9. Users with less than $25 in funds
SELECT USERNAME, BIRTHDAY, WALLETFUNDS
FROM USERBASE
WHERE WALLETFUNDS < 25;

-- 10. Users with more than 100 hours played
SELECT USERID, PRODUCTCODE
FROM USERLIBRARY
WHERE HOURSPLAYED > 100;

-- 11. Games with less than 10 hours played
SELECT PRODUCTCODE
FROM USERLIBRARY
WHERE HOURSPLAYED < 10;

-- 12. Unique publishers
SELECT DISTINCT PUBLISHER
FROM PRODUCTLIST;

-- 13. Products sorted by genre
SELECT PRODUCTNAME, RELEASEDATE, PUBLISHER, GENRE
FROM PRODUCTLIST
ORDER BY GENRE;

-- 14. Strategy genre products
SELECT PRODUCTCODE, PUBLISHER
FROM PRODUCTLIST
WHERE GENRE = 'Strategy';

-- 15. Products costing more than $25
SELECT PRODUCTCODE, PRICE
FROM STOREFRONT
WHERE PRICE > 25
ORDER BY PRICE DESC;

-- 16. Storefront sorted by price
SELECT INVENTORYID, PRICE
FROM STOREFRONT
ORDER BY PRICE ASC;

-- 17. Products with rating of 1
SELECT PRODUCTCODE, REVIEW
FROM REVIEWS
WHERE RATING = 1;

-- 18. Products with rating 4 or higher
SELECT PRODUCTCODE, REVIEW
FROM REVIEWS
WHERE RATING >= 4;

-- 19. Unique users who placed orders
SELECT DISTINCT USERID
FROM ORDERS;

-- 20. Orders sorted by earliest purchase date
SELECT *
FROM ORDERS
ORDER BY PURCHASEDATE;